// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5J17OV9C32u4zG6HMt8qGOxscFsrvkKc',
    appId: '1:376327673989:web:0364a61b585738321e31ec',
    messagingSenderId: '376327673989',
    projectId: 'bank-sampah-1ef03',
    authDomain: 'bank-sampah-1ef03.firebaseapp.com',
    storageBucket: 'bank-sampah-1ef03.appspot.com',
    measurementId: 'G-SEGJQFRPKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDG57FFpN3TxIAhm5w3_O4nOt74jsaPj4g',
    appId: '1:376327673989:android:5770c47d113693af1e31ec',
    messagingSenderId: '376327673989',
    projectId: 'bank-sampah-1ef03',
    storageBucket: 'bank-sampah-1ef03.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDS908VcfarXXsUbfECCJqDOZ2cddlKd5Q',
    appId: '1:376327673989:ios:74ce8180e2abc9271e31ec',
    messagingSenderId: '376327673989',
    projectId: 'bank-sampah-1ef03',
    storageBucket: 'bank-sampah-1ef03.appspot.com',
    iosBundleId: 'com.example.bankSampah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDS908VcfarXXsUbfECCJqDOZ2cddlKd5Q',
    appId: '1:376327673989:ios:74ce8180e2abc9271e31ec',
    messagingSenderId: '376327673989',
    projectId: 'bank-sampah-1ef03',
    storageBucket: 'bank-sampah-1ef03.appspot.com',
    iosBundleId: 'com.example.bankSampah',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5J17OV9C32u4zG6HMt8qGOxscFsrvkKc',
    appId: '1:376327673989:web:3d87b2a216d76f741e31ec',
    messagingSenderId: '376327673989',
    projectId: 'bank-sampah-1ef03',
    authDomain: 'bank-sampah-1ef03.firebaseapp.com',
    storageBucket: 'bank-sampah-1ef03.appspot.com',
    measurementId: 'G-DWRPE70JH1',
  );
}
